-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE sales_registers;
DROP TABLE products;
-- DROP TABLE users;


CREATE TABLE public.users
(
    _id serial NOT NULL,
    name text NOT NULL,
    last_name text NOT NULL,
    email text UNIQUE NOT NULL,
	password text NOT NULL,
    PRIMARY KEY (_id)
);

CREATE TABLE public.products
(
    _id serial NOT NULL,
    name text NOT NULL,
    url text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    _user_id integer NOT NULL,
    image_url text NOT NULL,
    status text NOT NULL,
    rgb integer[] NOT NULL,
    category text[],
    seller text NOT NULL,
    price numeric NOT NULL,
    "isBuybox" boolean NOT NULL,
    catalogue_id text,
    ml_id text,
    PRIMARY KEY (_id)
);

CREATE TABLE public.sales_registers
(
    _timestamp timestamp with time zone NOT NULL,
    daily_sells integer,
    acumulated_sells integer,
    dailly_visits integer,
    acumulated_visits integer,
    _product_id integer NOT NULL,
    PRIMARY KEY (_timestamp, _product_id)
);

ALTER TABLE public.products
    ADD FOREIGN KEY (_user_id)
    REFERENCES public.users (_id)
    NOT VALID;


ALTER TABLE public.sales_registers
    ADD FOREIGN KEY (_product_id)
    REFERENCES public.products (_id)
    NOT VALID;

END;